name: CI/CD to Heroku

on:
  push:
    branches:
      - main  # deploy on main branch push

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # adjust your Node.js version

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test # optional if you have Playwright or unit tests

      - name: Build project
        run: npm run build # optional

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
